/*
LeetCode 389 - Find the Difference

Topic: Strings, Hashing, Frequency Counting

Problem:
You are given two strings s and t.
String t is generated by randomly shuffling string s
and then adding one extra character.

Return the character that was added.

Approach:
1. Create a frequency array of size 26.
2. Count the occurrences of characters in s.
3. Traverse t and decrease the frequency.
4. If any frequency becomes negative,
   that character is the extra character.
5. Return the extra character.

Time Complexity: O(n)
Space Complexity: O(1)
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int[] freq = new int[26];

        for (int i = 0; i < s.length(); i++) {
            freq[s.charAt(i) - 'a']++;
        }

        for (int i = 0; i < t.length(); i++) {
            freq[t.charAt(i) - 'a']--;

            if (freq[t.charAt(i) - 'a'] < 0) {
                return t.charAt(i);
            }
        }

        return ' ';
    }
}
